CREATE DATABASE TASK1

USE TASK1

CREATE TABLE POSTS

(ID INT PRIMARY KEY IDENTITY,
POSTTEXT NVARCHAR (500) NOT NULL CONSTRAINT CK_PT CHECK(LEN(POSTTEXT)<500),
LIKECOUNT INT ,
CREATEDATE DATE DEFAULT GETDATE(),
TITLE NVARCHAR (255),
USERID INT REFERENCES USERS(ID) ,
)
INSERT INTO POSTS(POSTTEXT,LIKECOUNT,TITLE,USERID)
VALUES
('SALAM',45,'POSTTITLE',1),
('SALAM1',32,'POSTTITLE1',2),
('SALAM2',98,'POSTTITLE2',3),
('SALAM3',415,'POSTTITLE3',4)

CREATE TABLE USERS

(ID INT PRIMARY KEY IDENTITY ,
NAME NVARCHAR(500) NOT NULL,
SURNAME NVARCHAR(500),
EMAIL NVARCHAR (500) NOT NULL CONSTRAINT CK_EMAIL CHECK((LEN(EMAIL)>=4) AND (LEN(EMAIL)<=100))  

)

INSERT INTO USERS(NAME,SURNAME,EMAIL)
VALUES
('RESHAD','HAJIZADA','RESHADHAJIZADA@GMAIL.COM'),
('VUSAL','JAFAROV','VUSALJAFAROV@MAIL.RU'),
('RAUF','ELIYEV','RAUFELIYEV@MAIL.RU'),
('NESIMI','JAFAROV','NESIMIJAFAROV123@GMAIL.COM'),
('NIHAD','KERIMOV','NIHADKERIMOVV@GMAIL.COM')

CREATE TABLE USERPOST
(
ID INT PRIMARY KEY IDENTITY,
USERID INT REFERENCES USERS(ID),
POSTID INT REFERENCES POSTS(ID)

)

SELECT * FROM POSTS